name: 'medical_warehouse'
version: '1.0'
config-version: 2

profile: 'medical_warehouse'

model-paths: ["models"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
