medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: <DB_USER>
      password: <DB_PASSWORD>
      port: 5432
      dbname: <DB_NAME>
      schema: analytics
